# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='data'),
        ),
    ]
